\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{color}
\usepackage[landscape,pdftex]{geometry}
\usepackage{fancyhdr}

\DeclareOption{bigsym}{\DeclareSymbolFont{largesymbols}{OMX}{psycm}{m}{n}}
\ProcessOptions

\setlength{\oddsidemargin}{-0.75in}
\setlength{\evensidemargin}{-0.75in}
\setlength{\topmargin}{-1in}
\setlength{\textheight}{7.75in}
\setlength{\textwidth}{10.5in}
\setlength{\footskip}{0in}
\setlength{\parindent}{0pt}
\setlength{\rightskip}{0pt plus 1fil} % makes ragged right

\renewcommand{\familydefault}{phv} % helvetica

% following: color
\definecolor{mybgcolor}{rgb}{0,0,0.3125}
\definecolor{myyellow}{rgb}{1,1,0.4}
\definecolor{myblue}{rgb}{0.4,0.8,1}
\definecolor{mypink}{rgb}{1,0.4,1}
\definecolor{myhotpink}{rgb}{1,0,0.5}
\definecolor{mywhite}{rgb}{1,1,1}

% header/footer layout
\pagestyle{fancy}
\lhead{} \chead{} \rhead{}
\lfoot{} \cfoot{} \rfoot{\color{myyellow} \thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% font sizes
\newcommand{\superlarge}{\fontsize{60}{60} \selectfont}
\newcommand{\titlesize}{\fontsize{40}{50} \selectfont}
\newcommand{\headsize}{\fontsize{35}{35} \selectfont}
\newcommand{\textsize}{\fontsize{30}{35} \selectfont}
\newcommand{\smallsize}{\fontsize{25}{30} \selectfont}
\newcommand{\smallersize}{\fontsize{20}{25} \selectfont}
\newcommand{\smallestsize}{\fontsize{18}{22} \selectfont}
\newcommand{\evensmaller}{\fontsize{14}{18} \selectfont}
\newcommand{\lod}{\text{LOD}}
\newcommand{\bic}{\text{BIC}}
\newcommand{\rss}{\text{RSS}}
\newcommand{\var}{\text{var}}
\newcommand{\M}{\text{M}}
%\renewcommand{\log}{\text{log}}
%\renewcommand{\max}{\text{max}}


<<options, echo=FALSE, results="hide">>=
library(plotrix) # for draw.circle
opts_chunk$set(echo=FALSE, results="hide", echo=FALSE,
               fig.path="MoreFigs/", verbose=TRUE,
               fig.height=6.5, fig.width=10,
               fig.align="center")

# background colors
bgcolorpng <- rgb(0, 0, 98, maxColorValue=255)
bgcolor <- rgb(0, 0, 80, maxColorValue=255)
@

\pagecolor{mybgcolor}
\color{mywhite}

\begin{document}

\thispagestyle{empty}

\begin{center}
\titlesize \color{myyellow}

\vspace*{29.5mm}

{\headsize More on data visualization}

\vspace*{9.5mm}

\color{mypink}
\rule{10in}{1mm}
%\vspace{-10mm}

\vspace{10mm}

\textsize \color{myblue}
Karl W Broman
\vspace{5mm}

{\smallersize Department of Biostatistics \& Medical Informatics

University of Wisconsin -- Madison
\vspace{20mm}


\verb|www.biostat.wisc.edu/~kbroman|
}

\end{center}


\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{myblue} \smallersize
(things to be compared should be adjacent)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
par(bg=bgcolor, col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype", yaxt="n",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
axis(side=2, col.ticks="white", col.axis="white", col="white")
segments(xat, lo, xat, hi, lwd=2, col="white")
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col="white")
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col="white")
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col="white")
axis(side=1, at=xat, rep(c("Female", "Male"), 3), cex.axis=0.7,
     col="white", col.axis="white", col.lab="white")
axis(side=1, at=1:3, c("AA", "AB", "BB"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
par(bg=bgcolor, col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype", yaxt="n",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
axis(side=2, col.ticks="white", col.axis="white", col="white")
segments(xat, lo, xat, hi, lwd=2, col="white")
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col="white")
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col="white")
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col="white")
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     col="white", col.axis="white", col.lab="white")
axis(side=1, at=c(0.6, 1.8), c("Female", "Male"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)
@








\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{myblue} \smallersize
(add a bit of color)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex_color, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
pink <- rgb(255, 0, 128, maxColorValue=255)
blue <- rgb(0, 128, 255, maxColorValue=255)
col <- rep(c(pink, blue), 3)
par(bg=bgcolor, col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype", yaxt="n",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
axis(side=2, col.ticks="white", col.axis="white", col="white")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep("", 6), cex.axis=0.7,
     col="white", col.axis="white", col.lab="white")
for(i in seq(along=xat))
  axis(side=1, at=xat[i], rep(c("Female", "Male"), 3)[i], cex.axis=0.7,
       col="white", col.axis=col[i], col.lab=col[i], tick=FALSE)
axis(side=1, at=1:3, c("AA", "AB", "BB"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
col <- rep(c(pink, blue), rep(3, 2))
par(bg=bgcolor, col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype", yaxt="n",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
axis(side=2, col.ticks="white", col.axis="white", col="white")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     col="white", col.axis="white", col.lab="white")
for(i in 1:2)
  axis(side=1, at=c(0.6, 1.8)[i], c("Female", "Male")[i], col.axis=col[c(1,4)][i],
       tick=FALSE, line=2, cex.axis=1.3)
@



\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{myblue} \smallsize
(value $\propto$ {\color{mypink} radius})
\end{minipage}

\vfill

<<circles_messed_up>>=
gL <- c("Arabidopsis"=0.145, "Human" = 3.2, "Wheat"=17)

mult <- sqrt(gL["Human"]/pi)/gL["Human"]
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, 25), ylim=c(0, 25), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(20, 20, gL["Wheat"],     nv=251, lwd=2, border="wheat", col="wheat")
text(5/mult, 4/mult, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle( 1,  1,  gL["Arabidopsis"], nv=251, lwd=2, border="lightgreen", col="lightgreen")
text(1.3, 0.5, "Arabidopsis (0.145 Gbp)", col="lightgreen", adj=c(0, 0.5))
draw.circle( 4,  6,  gL["Human"],   nv=251, lwd=2, border="Orchid", col="Orchid")
text(4, 4, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@

\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{myblue} \smallsize
(value $\propto$ area)
\end{minipage}

\vfill

<<circles_fixed>>=
mx <- 25*mult
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, mx), ylim=c(0, mx), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(5, 4, sqrt(gL["Wheat"]/pi),     nv=251, lwd=2, border="wheat", col="wheat")
text(5, 4, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle(mult*0.9, mult*1.7, sqrt(gL["Arabidopsis"]/pi), nv=251, lwd=2, border="lightgreen", col="lightgreen")
text(1.3*mult, 0.5*mult, "Arabidopsis (0.145 Gbp)", col="lightgreen", adj=c(0, 0.5))
draw.circle(4*mult,  6*mult,  sqrt(gL["Human"]/pi),   nv=251, lwd=2, border="Orchid", col="Orchid")
text(4*mult, 4*mult, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@


\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't use areas at all

\color{myblue} \smallsize
(value $\propto$ length)
\end{minipage}

\vfill

<<circles_barplot,fig.width=6.5>>=
par(mar=c(3.1, 5.1, 0.6, 0.6), bg=bgcolor, col="white",
    col.lab="white", col.axis="white")
b <- barplot(gL, col=c("lightgreen", "Orchid", "wheat"), ylab="Genome size (Gbp)",
             ylim=c(0, 18), col.lab="white", yaxs="i", yaxt="n",
             names.arg=rep("", 3), cex.lab=1.5)
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")
axis(side=2, col.axis="white", las=1, col="white", cex.axis=1.5)
axis(side=1, at=b, names(gL), col.axis="white", las=1, col="white",
     cex.axis=1.5, tick=FALSE)
@

\end{document}
