\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{color}
\usepackage[landscape,pdftex]{geometry}
\usepackage{fancyhdr}

\DeclareOption{bigsym}{\DeclareSymbolFont{largesymbols}{OMX}{psycm}{m}{n}}
\ProcessOptions

\setlength{\oddsidemargin}{-0.75in}
\setlength{\evensidemargin}{-0.75in}
\setlength{\topmargin}{-1in}
\setlength{\textheight}{7.75in}
\setlength{\textwidth}{10.5in}
\setlength{\footskip}{0in}
\setlength{\parindent}{0pt}
\setlength{\rightskip}{0pt plus 1fil} % makes ragged right

\renewcommand{\familydefault}{phv} % helvetica

% following: color
\definecolor{mybgcolor}{rgb}{0,0,0.3125}
\definecolor{myyellow}{rgb}{1,1,0.4}
\definecolor{myblue}{rgb}{0.4,0.8,1}
\definecolor{mypink}{rgb}{1,0.4,1}
\definecolor{myhotpink}{rgb}{1,0,0.5}
\definecolor{mywhite}{rgb}{1,1,1}

% header/footer layout
\pagestyle{fancy}
\lhead{} \chead{} \rhead{}
\lfoot{} \cfoot{} \rfoot{\color{myyellow} \thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% font sizes
\newcommand{\superlarge}{\fontsize{60}{60} \selectfont}
\newcommand{\titlesize}{\fontsize{40}{50} \selectfont}
\newcommand{\headsize}{\fontsize{35}{35} \selectfont}
\newcommand{\textsize}{\fontsize{30}{35} \selectfont}
\newcommand{\smallsize}{\fontsize{25}{30} \selectfont}
\newcommand{\smallersize}{\fontsize{20}{25} \selectfont}
\newcommand{\smallestsize}{\fontsize{18}{22} \selectfont}
\newcommand{\evensmaller}{\fontsize{14}{18} \selectfont}
\newcommand{\lod}{\text{LOD}}
\newcommand{\bic}{\text{BIC}}
\newcommand{\rss}{\text{RSS}}
\newcommand{\var}{\text{var}}
\newcommand{\M}{\text{M}}
%\renewcommand{\log}{\text{log}}
%\renewcommand{\max}{\text{max}}


<<options, echo=FALSE, results="hide">>=
library(plotrix) # for draw.circle
opts_chunk$set(echo=FALSE, results="hide", echo=FALSE,
               fig.path="MoreFigs/", verbose=TRUE,
               fig.height=6.5, fig.width=10,
               fig.align="center")

# background colors
bgcolorpng <- rgb(0, 0, 98, maxColorValue=255)
bgcolor <- rgb(0, 0, 80, maxColorValue=255)
@

\pagecolor{mybgcolor}
\color{mywhite}

\begin{document}

\thispagestyle{empty}

\begin{center}
\titlesize \color{myyellow}

\vspace*{29.5mm}

{\headsize More on data visualization}

\vspace*{9.5mm}

\color{mypink}
\rule{10in}{1mm}
%\vspace{-10mm}

\vspace{10mm}

\textsize \color{myblue}
Karl W Broman
\vspace{5mm}

{\smallersize Department of Biostatistics \& Medical Informatics

University of Wisconsin -- Madison
\vspace{20mm}


\verb|www.biostat.wisc.edu/~kbroman|
}

\end{center}


\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{myblue} \smallersize
(things to be compared should be adjacent)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
par(bg=bgcolor, fg="white", col="white", las=1, col.axis="white",
    col.lab="white")
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
segments(xat, lo, xat, hi, lwd=2)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2)
axis(side=1, at=xat, rep(c("Female", "Male"), 3), cex.axis=0.7,
     fg="white", col.axis="white")
axis(side=1, at=1:3, c("AA", "AB", "BB"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
segments(xat, lo, xat, hi, lwd=2)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2)
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     fg="white", col.axis="white")
axis(side=1, at=c(0.6, 1.8), c("Female", "Male"), col.axis="white",
     tick=FALSE, line=2, cex.axis=1.3)
@








\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Ease comparisons

\bigskip

\color{myblue} \smallersize
(add a bit of color)
\end{minipage}

\vspace{10mm}

<<genotype_and_sex_color, fig.height=5.5>>=
par(mfrow=c(1,2))
set.seed(11341)
me <- c(10, 15, 17, 12, 16, 18)
se <- runif(length(me), 0.5, 1)
me <- me[c(1,4,2,5,3,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(1, 2, 3)
xat <- sort(c(xat - xd, xat + xd))
pink <- rgb(255, 0, 128, maxColorValue=255)
blue <- rgb(0, 128, 255, maxColorValue=255)
col <- rep(c(pink, blue), 3)
par(bg=bgcolor, fg="white", col="white", col.axis="white", col.lab="white",
    las=1)
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep("", 6), cex.axis=0.7)
for(i in seq(along=xat))
  axis(side=1, at=xat[i], rep(c("Female", "Male"), 3)[i], cex.axis=0.7,
       col="white", col.axis=col[i], tick=FALSE)
axis(side=1, at=1:3, c("AA", "AB", "BB"),
     tick=FALSE, line=2, cex.axis=1.3)


me <- me[c(1,3,5,2,4,6)]
se <- se[c(1,3,5,2,4,6)]
lo <- me - se
hi <- me + se
xd <- 0.2
xat <- c(0.3, 0.6, 0.9, 1.5, 1.8, 2.1)
col <- rep(c(pink, blue), rep(3, 2))
plot(0, 0, type="n", xlab="", xaxt="n", ylab="Phenotype",
     ylim=range(c(lo, hi))+c(-1, +1), xlim=range(xat)+c(-xd, xd)*2,
     xaxs="i", yaxs="i")
abline(h=pretty(c(lo, hi)), col="gray20")
segments(xat, lo, xat, hi, lwd=2, col=col)
segments(xat-xd/8, lo, xat+xd/8, lo, lwd=2, col=col)
segments(xat-xd/8, hi, xat+xd/8, hi, lwd=2, col=col)
segments(xat-xd/4, me, xat+xd/4, me, lwd=2, col=col)
axis(side=1, at=xat, rep(c("AA", "AB", "BB"), 2),
     col="white", col.axis="white")
for(i in 1:2)
  axis(side=1, at=c(0.6, 1.8)[i], c("Female", "Male")[i], col.axis=col[c(1,4)][i],
       tick=FALSE, line=2, cex.axis=1.3)
@



\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.75in}
\centering
Which comparison is easiest?
\end{minipage}

\vfill

<<many_plots, >>=
par(mfrow=c(2,3), bg=bgcolor, col="white",
    col.axis="white", col.lab="white", las=1,
    mar=c(4.1, 4.1, 1.1, 1.1))
ht <- c(83, 114, 36, 67, 114, 154, 137)
names(ht) <- rep("", length(ht))
names(ht)[4:5] <- c("A", "B")
col <- rep(bgcolor, length(ht))
col[4:5] <- c(pink, blue)

barplot(ht, col=col, border="white", ylim=c(0, max(ht)*1.1))
axis(side=2, col.axis="white", col.ticks="white", col.lab="white")
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")


o <- c(4, 2, 3, 1, 5, 6, 7)
barplot(ht[o], col=col[o], border="white", ylim=c(0, max(ht)*1.1))
axis(side=2, col.axis="white", col.ticks="white", col.lab="white")
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")

htlist <- list(ht[o][1:4], ht[o][5:7])
collist <- list(col[o][1:4], col[o][5:7])
lablist <- list(names(ht)[o][1:4], names(ht)[o][5:7])
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i", col="white", las=1)
axis(side=2, col.axis="white", col.ticks="white", col.lab="white", col="white")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

htlist[[2]] <- rev(htlist[[2]])
collist[[2]] <- rev(collist[[2]])
lablist[[2]] <- rev(lablist[[2]])
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i", col="white", las=1)
axis(side=2, col.axis="white", col.ticks="white", col.lab="white", col="white")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

collist[[1]][2] <- collist[[2]][3]
collist[[2]][3] <- collist[[2]][2]
lablist[[1]][2] <- lablist[[2]][3]
lablist[[2]][3] <- lablist[[2]][2]
plot(0, 0, type="n", xaxt="n", xlab="", ylab="", xlim=c(0.5, 2.5),
     ylim=c(0, max(sapply(htlist, sum))*1.1), yaxs="i", xaxs="i", col="white", las=1)
axis(side=2, col.axis="white", col.ticks="white", col.lab="white", col="white")
xl <- c(0.75, 1.65)
xr <- c(1.35, 2.25)
for(i in 1:2) {
  top <- cumsum(htlist[[i]])
  bot <- cumsum(c(0, htlist[[i]]))
  for(j in seq(along=htlist[[i]])) {
    rect(xl[i], bot[j], xr[i], top[j], border="white",
         col=collist[[i]][j])
    text((xl[i] + xr[i])/2, (bot[j]+top[j])/2, lablist[[i]][j], col=bgcolor)
  }
}

o <- c(1,2,3,5,6,4,7)
pie(ht[o], col=col[o], border="white")
@



\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{myblue} \smallsize
(value $\propto$ {\color{mypink} radius})
\end{minipage}

\vfill

<<circles_messed_up>>=
gL <- c("Arabidopsis"=0.145, "Human" = 3.2, "Wheat"=17)

mult <- sqrt(gL["Human"]/pi)/gL["Human"]
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, 25), ylim=c(0, 25), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(20, 20, gL["Wheat"],     nv=251, lwd=2, border="wheat", col="wheat")
text(5/mult, 4/mult, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle( 1,  1,  gL["Arabidopsis"], nv=251, lwd=2, border="lightgreen", col="lightgreen")
text(1.3, 0.5, "Arabidopsis (0.145 Gbp)", col="lightgreen", adj=c(0, 0.5))
draw.circle( 4,  6,  gL["Human"],   nv=251, lwd=2, border="Orchid", col="Orchid")
text(4, 4, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@

\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't distort the quantities

\color{myblue} \smallsize
(value $\propto$ area)
\end{minipage}

\vfill

<<circles_fixed>>=
mx <- 25*mult
par(mar=rep(0.1, 4), bg=bgcolor, col="white")
plot(0,0,type="n", xlim=c(0, mx), ylim=c(0, mx), xlab="", ylab="",
     xaxt="n", yaxt="n", xaxs="i", yaxs="i")
draw.circle(5, 4, sqrt(gL["Wheat"]/pi),     nv=251, lwd=2, border="wheat", col="wheat")
text(5, 4, "Wheat (17 Gbp)", col=bgcolor, cex=1.5)
draw.circle(mult*0.9, mult*1.7, sqrt(gL["Arabidopsis"]/pi), nv=251, lwd=2, border="lightgreen", col="lightgreen")
text(1.3*mult, 0.5*mult, "Arabidopsis (0.145 Gbp)", col="lightgreen", adj=c(0, 0.5))
draw.circle(4*mult,  6*mult,  sqrt(gL["Human"]/pi),   nv=251, lwd=2, border="Orchid", col="Orchid")
text(4*mult, 4*mult, "Human (3.2 Gbp)", col=bgcolor, adj=c(0.5, 0.5))
@


\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{6.25in}
\centering
Don't use areas at all

\color{myblue} \smallsize
(value $\propto$ length)
\end{minipage}

\vfill

<<circles_barplot,fig.width=6.5>>=
par(mar=c(3.1, 5.1, 0.6, 0.6), bg=bgcolor, col="white",
    col.lab="white", col.axis="white")
b <- barplot(gL, col=c("lightgreen", "Orchid", "wheat"), ylab="Genome size (Gbp)",
             ylim=c(0, 18), col.lab="white", yaxs="i", yaxt="n",
             names.arg=rep("", 3), cex.lab=1.5)
u <- par("usr")
rect(u[1], u[3], u[2], u[4], border="white")
axis(side=2, col.axis="white", las=1, col="white", cex.axis=1.5)
axis(side=1, at=b, names(gL), col.axis="white", las=1, col="white",
     cex.axis=1.5, tick=FALSE)
@



\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{5.75in}
\centering
Encoding data
\end{minipage}

\vspace{30mm}

\smallersize \color{mywhite}
\hspace{1in} \begin{minipage}[t]{4in}
\vspace*{0mm}

{\smallsize \color{mypink} Quantities}
\vspace{5mm}

\begin{itemize}
\item Position
\item Length
\item Angle
\item Area
\item Luminance {\color{myblue} (light/dark)}
\item Chroma {\color{myblue} (amount of color)}
\end{itemize}

\end{minipage}
\hfill
\begin{minipage}[t]{4in}
\vspace*{0mm}

{\smallsize \color{mypink} Categories}
\vspace{5mm}

\begin{itemize}
\item Shape
\item Hue {\color{myblue} (which color)}
\item Texture
\item Width
\end{itemize}

\end{minipage}

\newpage


\headsize \color{myyellow}
\hfill
\begin{minipage}{5.75in}
\centering
Inspirations
\end{minipage}

\vspace{30mm}

\smallersize \color{mywhite}
\hspace{0.5in} \begin{minipage}{9.5in}

\begin{itemize}
\item Hadley Wickham
{\smallestsize \color{myblue}
(slides at \verb|http://courses.had.co.nz|)}

\item Naomi Robbins
{\smallestsize \color{myblue}
(\emph{Creating more effective graphs})}

\item Howard Wainer

\item Andrew Gelman

\item Edward Tufte

\end{itemize}

\end{minipage}




\end{document}
